@startuml
class com.example.firebasetest.GameView {
~ Context context
+ {static} float width
+ {static} float height
+ {static} float pixelWidth
+ {static} float pixelHeight
+ {static} float canvasPixelHeight
~ Thread gameThread
+ void run()
+ void resume()
}


class com.example.firebasetest.Knight {
+ {static} Bitmap knightSprite
- boolean shielded
- boolean parry
- int shieldHP
- int horseHP
- int maxShieldHP
- int maxHorseHP
- float horseDirection
- boolean mounted
+ void Attack()
+ boolean shieldOrParry(int)
+ void shieldHeld()
+ void shieldReleased()
+ void parry()
+ void unParry()
+ void buff()
+ void deBuff()
+ void mount(Bitmap)
+ void dismount()
+ boolean hit(Projectile)
- void poisonedHorse(int)
+ boolean horsePoison(int)
+ void shieldRestore()
+ void horseRestore()
+ void run()
+ int getRandomNumber(int,int)
}


class com.example.firebasetest.UnParry {
- Knight knight
+ void run()
}


class com.example.firebasetest.DeBuff {
- Knight knight
+ void run()
}


class com.example.firebasetest.RestoreHorse {
- Knight knight
+ void run()
}


class com.example.firebasetest.RestoreShield {
- Knight knight
+ void run()
}


class com.example.firebasetest.Poison {
- Knight knight
- int repeats
- int power
+ void run()
}


class com.example.firebasetest.Room {
- int sectionNum
- int floorNum
- int roomNum
- String roomClass
- Thread roomThread
- ArrayList<Character> characters
- ArrayList<Projectile> projectiles
- ArrayList<GameObject> objects
+ ArrayList<GameObject> getObjects()
+ void run()
}


class com.example.firebasetest.Archer {
+ {static} Bitmap archerSprite
- {static} Bitmap arrowSprite
- boolean homing
- boolean ricochet
- float arrowSpeed
- boolean isPoison
- float physicalArrowSpeed
+ void shoot()
+ void stab()
+ void poison()
+ boolean homing()
+ void notHoming()
+ void run()
}


class com.example.firebasetest.NotHoming {
- Archer archer
+ void run()
}


class com.example.firebasetest.MainActivity {
+ {static} boolean signIn
+ {static} boolean success
- FirebaseAuth mAuth
# void onCreate(Bundle)
- void moveToNextActivity()
+ void signUp(View)
+ void signIn(View)
- void signUpOrIn(View)
- void addUser()
}


class com.example.firebasetest.GameObject {
- Bitmap sprite
- float widthPercentage
- float heightPercentage
- float xPercentage
- float yPercentage
# int roomID
+ float getWidthPercentage()
+ void setWidthPercentage(float)
+ float getHeightPercentage()
+ void setHeightPercentage(float)
+ float getXPercentage()
+ void setXPercentage(float)
+ float getYPercentage()
+ void setYPercentage(float)
}


class com.example.firebasetest.BladeAttack {
- long TTD
+ long getTTD()
}


class com.example.firebasetest.LightLine {
- boolean isLaser
}

class com.example.firebasetest.Projectile {
# float horizontalSpeed
# float verticalSpeed
# float power
# Character creator
+ float getHorizontalSpeed()
+ void setHorizontalSpeed(float)
+ float getVerticalSpeed()
+ void setVerticalSpeed(float)
+ float getPower()
+ void setPower(float)
+ void setCreator(Character)
}


class com.example.firebasetest.Mist {
- long TTD
+ long getTTD()
}


class com.example.firebasetest.User {
- String email
- int level
- String className
- String[] order
- int enemyDifficulty
- int difficultyScaling
- int challengeDifficulty
- int challengeDifficultyScaling
- int doomsdayClock
- int suddenDeath
- int currentSection
- int currentFloor
- int currentRoom
+ int getLevel()
+ void setLevel(int)
+ String getClassName()
+ void setClassName(String)
+ String[] getOrder()
+ void setOrder(String[])
+ int getEnemyDifficulty()
+ void setEnemyDifficulty(int)
+ int getDifficultyScaling()
+ void setDifficultyScaling(int)
+ int getChallengeDifficulty()
+ void setChallengeDifficulty(int)
+ int getChallengeDifficultyScaling()
+ void setChallengeDifficultyScaling(int)
+ int getDoomsdayClock()
+ void setDoomsdayClock(int)
+ int getSuddenDeath()
+ void setSuddenDeath(int)
+ int getCurrentSection()
+ void setCurrentSection(int)
+ int getCurrentFloor()
+ void setCurrentFloor(int)
+ int getCurrentRoom()
+ void setCurrentRoom(int)
+ String getEmail()
}


class com.example.firebasetest.Arrow {
- boolean ricochet
- boolean homing
- boolean poison
+ boolean isPoison()
}


class com.example.firebasetest.Character {
- {static} Character player
# int HP
# long attackCooldown
# int attackPower
# Bitmap itemSprite
# float itemWidth
# float itemHeight
# ArrayList<Projectile> projectiles
- boolean listSent
# float horizontalDirection
# float verticalDirection
- long resetX
- long resetY
- long resetB
- long resetA
# float movementSpeed
# float horizontalMovement
# float verticalMovement
# Thread thread
# int characterGrade
# int locked
# boolean running
# boolean threadStart
# boolean moving
# int legsPos
# ArrayList<Projectile> getProjectiles()
# void emptyList()
+ ArrayList<Projectile> getProjectileList(int,ArrayList<Character>)
+ void switchSizes()
+ boolean useAbility(String)
+ void resetAbility(String)
+ boolean hit(Projectile)
- void poisoned(int)
- void poison(int)
+ void freeze()
+ void unFreeze()
+ void Attack()
+ {static} void setPlayer(Character)
# {static} float getPlayerX()
# {static} float getPlayerY()
# {static} float getPlayerWidth()
# {static} float getPlayerHeight()
# void move(float,float,float,float)
+ boolean inRange()
+ float[] aimAtPlayer()
+ boolean aim(float,float,float)
- boolean ceiling(double,double)
- boolean faster(double,double,double,double,double)
- double[] arcTan(double,double,double)
+ void run()
}


class com.example.firebasetest.Poison {
- Character chr
- int repeats
- int power
+ void run()
}


class com.example.firebasetest.UnFreeze {
- Character chr
+ void run()
}


class com.example.firebasetest.FireBall {
}
class com.example.firebasetest.Mage {
+ {static} Bitmap mageSprite
- Bitmap lineSprite
- Bitmap fireSprite
- Bitmap mistSprite
- int maxHealth
+ void lightLine()
+ void mist()
+ void fireball()
+ void heal()
}


class com.example.firebasetest.GameActivity {
~ GameView gameView
~ User playerUser
# void onCreate(Bundle)
+ void ReadDataFromFB(View)
# void onResume()
}




com.example.firebasetest.Runnable <|.. com.example.firebasetest.GameView
android.view.SurfaceView <|-- com.example.firebasetest.GameView
com.example.firebasetest.Character <|-- com.example.firebasetest.Knight
com.example.firebasetest.TimerTask <|-- com.example.firebasetest.UnParry
com.example.firebasetest.TimerTask <|-- com.example.firebasetest.DeBuff
com.example.firebasetest.TimerTask <|-- com.example.firebasetest.RestoreHorse
com.example.firebasetest.TimerTask <|-- com.example.firebasetest.RestoreShield
com.example.firebasetest.TimerTask <|-- com.example.firebasetest.Poison
com.example.firebasetest.Runnable <|.. com.example.firebasetest.Room
com.example.firebasetest.Character <|-- com.example.firebasetest.Archer
com.example.firebasetest.TimerTask <|-- com.example.firebasetest.NotHoming
androidx.appcompat.app.AppCompatActivity <|-- com.example.firebasetest.MainActivity
com.example.firebasetest.Projectile <|-- com.example.firebasetest.BladeAttack
com.example.firebasetest.Projectile <|-- com.example.firebasetest.LightLine
com.example.firebasetest.GameObject <|-- com.example.firebasetest.Projectile
com.example.firebasetest.Projectile <|-- com.example.firebasetest.Mist
com.example.firebasetest.Projectile <|-- com.example.firebasetest.Arrow
com.example.firebasetest.Runnable <|.. com.example.firebasetest.Character
com.example.firebasetest.GameObject <|-- com.example.firebasetest.Character
com.example.firebasetest.TimerTask <|-- com.example.firebasetest.Poison
com.example.firebasetest.TimerTask <|-- com.example.firebasetest.UnFreeze
com.example.firebasetest.Projectile <|-- com.example.firebasetest.FireBall
com.example.firebasetest.Character <|-- com.example.firebasetest.Mage
androidx.appcompat.app.AppCompatActivity <|-- com.example.firebasetest.GameActivity
@enduml